import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { buildImageGenerationRequest, generateImage } from '../services/media/image-generation.js';
import { MAX_GENERATED_SVG_BYTES, sanitizeGeneratedSvg } from '../services/media/svg-generation.js';

test('builds a Cockpit image generation request from synced Magento settings', () => {
    const request = buildImageGenerationRequest('A friendly brown puppy', {
        provider: 'cockpit',
        api_key: 'test-key',
        base_url: 'http://127.0.0.1:49998/v1',
        image_generation: {
            enabled: true,
            model: 'gpt-image-2',
            size: '1536x1024',
            quality: 'low'
        }
    });

    assert.equal(request.model, 'gpt-image-2');
    assert.equal(request.size, '1536x1024');
    assert.equal(request.quality, 'low');
    assert.deepEqual(request.body, {
        model: 'gpt-image-2',
        prompt: 'A friendly brown puppy',
        size: '1536x1024',
        quality: 'low',
        output_format: 'png'
    });
});

test('falls back to safe image defaults for unsupported dimensions and quality', () => {
    const request = buildImageGenerationRequest('A simple icon', {
        provider: 'cockpit',
        api_key: 'test-key',
        base_url: 'http://127.0.0.1:49998/v1',
        image_generation: {
            model: 'gpt-image-2',
            size: '999x999',
            quality: 'ultra'
        }
    });

    assert.equal(request.size, '1024x1024');
    assert.equal(request.quality, 'medium');
});

test('builds a native Gemini image-generation request from the shared image tool', () => {
    const request = buildImageGenerationRequest('A simple icon', {
        provider: 'gemini',
        api_key: 'test-key',
        base_url: 'https://generativelanguage.googleapis.com/v1beta',
        image_generation: { model: 'gpt-image-2', size: '1536x1024' }
    });

    assert.equal(request.model, 'gemini-3.1-flash-image');
    assert.deepEqual(request.body.generationConfig.responseModalities, ['IMAGE']);
    assert.equal(request.body.generationConfig.responseFormat.image.aspectRatio, 'ASPECT_RATIO_3_2');
    assert.equal(request.body.generationConfig.responseFormat.image.imageSize, 'IMAGE_SIZE_1K');
});

test('uses the Responses image tool for an explicitly capable model', () => {
    const request = buildImageGenerationRequest('A store mascot wearing a scarf', {
        provider: 'cockpit-tool',
        api_key: 'test-key',
        base_url: 'https://provider.example/v1',
        api_format: 'openai-responses',
        model: 'gpt-5.6-terra',
        models: [{
            id: 'gpt-5.6-terra',
            supports_images: true,
            image_transport: 'openai-responses'
        }],
        image_generation: { enabled: true, size: '1024x1024', quality: 'high' }
    });

    assert.equal(request.transport, 'openai-responses');
    assert.deepEqual(request.body, {
        model: 'gpt-5.6-terra',
        input: 'A store mascot wearing a scarf',
        tools: [{
            type: 'image_generation',
            action: 'generate',
            size: '1024x1024',
            quality: 'high'
        }]
    });
});

test('refuses an Anthropic-compatible tunnel unless the selected model declares an image API', () => {
    assert.throws(() => buildImageGenerationRequest('A poster', {
        provider: 'gemini-tunnel',
        api_key: 'test-key',
        base_url: 'https://provider.example/v1',
        api_format: 'anthropic-messages',
        model: 'ag/gemini-3.6-flash-high',
        models: [{ id: 'ag/gemini-3.6-flash-high', supports_images: false }],
        image_generation: { enabled: true }
}), /does not have a configured image-generation API/);
});

test('sanitizes a self-contained SVG while preserving SVG case-sensitive names', () => {
    const svg = sanitizeGeneratedSvg(
        '<?xml version="1.0" encoding="UTF-8"?>\n<!-- generated by the model -->\n<svg viewBox="0 0 20 20"><linearGradient id="g"><stop offset="0%" stop-color="#fff" /></linearGradient><rect width="20" height="20" fill="url(#g)" /></svg>'
    );

    assert.match(svg, /<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" viewBox=/);
    assert.match(svg, /<linearGradient/);
    assert.match(svg, /<stop offset="0%" stop-color="#fff" \/>/);
    assert.throws(
        () => sanitizeGeneratedSvg('<svg><script>alert(1)</script></svg>'),
        /forbidden element or declaration/
    );
    assert.throws(
        () => sanitizeGeneratedSvg('<svg><image href="https://attacker.example/a.png" /></svg>'),
        /not allowed|external references/
    );
    assert.throws(
        () => sanitizeGeneratedSvg('<!DOCTYPE svg [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><svg />'),
        /forbidden element or declaration/
    );
    assert.throws(
        () => sanitizeGeneratedSvg(`<svg>${'x'.repeat(MAX_GENERATED_SVG_BYTES)}</svg>`),
        /larger than the permitted/
    );
});

test('supports the safe SVG filter primitives used by ZCode-style artwork', () => {
    const svg = sanitizeGeneratedSvg(
        '<svg viewBox="0 0 100 100"><defs><filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur" /><feOffset in="blur" dx="2" dy="2" result="offset" /><feFlood flood-color="#000" flood-opacity=".25" result="color" /><feComposite in="color" in2="offset" operator="in" result="shadow" /><feMerge><feMergeNode in="shadow" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs><rect x="10" y="10" width="80" height="80" rx="8" fill="#2d7cff" filter="url(#shadow)" /></svg>'
    );

    assert.match(svg, /<filter id="shadow"/);
    assert.match(svg, /<feGaussianBlur[^>]+stdDeviation="3"/);
    assert.match(svg, /<feMergeNode in="SourceGraphic" \/>/);
    assert.throws(
        () => sanitizeGeneratedSvg('<svg><filter><feImage href="https://attacker.example/x" /></filter></svg>'),
        /SVG element "feimage" is not allowed/
    );
});

test('creates a safe SVG fallback with a chat-only model and emits the normal image event contract', async () => {
    const directory = path.resolve(new URL('../.test-generated-svg', import.meta.url).pathname);
    process.env.AI_GENERATED_IMAGE_DIRECTORY = directory;
    process.env.AI_GENERATED_IMAGE_PUBLIC_BASE_URL = 'https://shop.example';
    const events = [];
    try {
        const result = await generateImage({
            prompt: 'A friendly store mascot',
            svgContent: '<svg viewBox="0 0 10 10"><circle cx="5" cy="5" r="4" fill="#123456" /></svg>',
            config: {
                provider: 'gemini-tunnel',
                api_key: 'chat-key',
                models: [{ id: 'ag/gemini-3.6-flash-high', supports_images: false }],
                model: 'ag/gemini-3.6-flash-high',
                image_generation: { enabled: true, minimum_display_ms: 0 }
            },
            ws: { send: (value) => events.push(JSON.parse(value)) }
        });

        assert.equal(result.mime_type, 'image/svg+xml');
        assert.match(result.url, /^https:\/\/shop\.example\/media\/afd-ai\/generated\/.*\.svg$/);
        assert.equal(events[0].type, 'image_generation_started');
        assert.equal(events.at(-1).type, 'image_generated');
        const filename = path.basename(new URL(result.url).pathname);
        const stored = await fs.readFile(path.join(directory, filename), 'utf8');
        assert.match(stored, /<circle/);
    } finally {
        await fs.rm(directory, { recursive: true, force: true });
        delete process.env.AI_GENERATED_IMAGE_DIRECTORY;
        delete process.env.AI_GENERATED_IMAGE_PUBLIC_BASE_URL;
    }
});

test('keeps the SVG creation placeholder visible for the configured minimum duration', async () => {
    const directory = path.resolve(new URL('../.test-generated-svg-delay', import.meta.url).pathname);
    process.env.AI_GENERATED_IMAGE_DIRECTORY = directory;
    try {
        const startedAt = Date.now();
        await generateImage({
            prompt: 'A simple circle',
            svgContent: '<svg><circle cx="5" cy="5" r="4" /></svg>',
            config: { image_generation: { enabled: true, minimum_display_ms: 35 } }
        });
        assert.ok(Date.now() - startedAt >= 25);
    } finally {
        await fs.rm(directory, { recursive: true, force: true });
        delete process.env.AI_GENERATED_IMAGE_DIRECTORY;
    }
});
