import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { sealConfig, unsealConfig } from './config-seal.js';
import { getProviderCapabilities, validateProviderConfiguration } from '../providers/provider-capabilities.js';
import { defaultImageTransport, normalizeImageTransport } from '../media/image-transport.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// `__dirname` is `services/configuration`; configuration is operational state
// for the whole gateway, not a file inside the source services directory.
// Keeping it beside the gateway logs also makes a restart read the same
// snapshot that Magento last synchronized.
const CONFIG_DIRECTORY = process.env.AI_CONFIG_DIRECTORY || path.join(__dirname, '../../.local');
const CONFIG_FILE = process.env.AI_CONFIG_FILE || path.join(CONFIG_DIRECTORY, 'ai-config.json');
const MAGENTO_OAUTH_FIELDS = [
    'consumer_key',
    'consumer_secret',
    'access_token',
    'access_token_secret'
];
const IMAGE_SIZES = new Set(['1024x1024', '1536x1024', '1024x1536']);
const IMAGE_QUALITIES = new Set(['low', 'medium', 'high']);
const API_FORMATS = new Set(['anthropic-messages', 'openai-chat-completions', 'openai-responses']);
const THOUGHT_LEVELS = new Set(['low', 'medium', 'high', 'xhigh']);
const TENANT_ID_PATTERN = /^[a-f0-9]{64}$/i;

let cachedConfig = null;
const STORE_CODE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;

function readString(value, fallback = '') {
    return typeof value === 'string' ? value.trim() : fallback;
}

/** Tenant IDs are generated by Magento from its installation base URL. */
export function normalizeTenantId(value) {
    const tenantId = readString(value).toLowerCase();
    return TENANT_ID_PATTERN.test(tenantId) ? tenantId : '';
}

function normalizeProviderModels(value) {
    if (!Array.isArray(value)) return [];
    return value.map((model) => {
        const source = model && typeof model === 'object' && !Array.isArray(model) ? model : {};
        const id = readString(source.id || source.model_id || source.modelId);
        if (!id) return null;
        const reasoningEnabled = normalizeBoolean(source.reasoning_enabled ?? source.reasoning, false);
        const levels = Array.isArray(source.reasoning_levels ?? source.thought_levels)
            ? (source.reasoning_levels ?? source.thought_levels)
                .map((level) => readString(level).toLowerCase())
                .filter((level, index, all) => THOUGHT_LEVELS.has(level) && all.indexOf(level) === index)
            : [];
        const imageTransport = normalizeImageTransport(
            source.image_transport
            ?? source.imageTransport
            ?? source.image_generation?.transport
        );
        const supportsImages = normalizeBoolean(source.supports_images ?? source.supportsImages, false);
        const rawMaxOutputTokens = source.max_output_tokens ?? source.maxOutputTokens;
        const hasMaxOutputTokens = rawMaxOutputTokens !== undefined
            && rawMaxOutputTokens !== null
            && String(rawMaxOutputTokens).trim() !== '';
        const maxOutputConfigured = Object.prototype.hasOwnProperty.call(source, 'max_output_tokens_configured')
            ? normalizeBoolean(source.max_output_tokens_configured, false)
            : (hasMaxOutputTokens && Number(rawMaxOutputTokens) !== 8192);
        return {
            id,
            name: readString(source.name, id),
            context_window: clampInteger(source.context_window ?? source.contextWindow, 128000, 1000, 2_000_000),
            max_output_tokens: maxOutputConfigured
                ? clampInteger(rawMaxOutputTokens, 0, 256, 128000)
                : null,
            max_output_tokens_configured: maxOutputConfigured,
            reasoning_enabled: reasoningEnabled,
            reasoning_levels: reasoningEnabled && levels.length > 0
                ? levels
                : (reasoningEnabled ? ['low', 'medium', 'high', 'xhigh'] : []),
            reasoning_default_level: THOUGHT_LEVELS.has(readString(source.reasoning_default_level).toLowerCase())
                ? readString(source.reasoning_default_level).toLowerCase()
                : '',
            supports_tools: normalizeBoolean(source.supports_tools ?? source.supportsTools, true),
            supports_images: supportsImages,
            image_transport: supportsImages ? imageTransport : '',
            image_model: readString(source.image_model ?? source.imageModel)
        };
    }).filter(Boolean);
}

function normalizeProviderEntry(value, code = '') {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};
    const providerCode = readString(source.provider_code || source.code || source.id, code);
    const apiFormat = readString(source.api_format || source.apiFormat, 'openai-chat-completions');
    return {
        provider_id: Number.isFinite(Number(source.provider_id)) ? Number(source.provider_id) : null,
        name: readString(source.name, providerCode || 'Custom Provider'),
        code: providerCode,
        provider_code: providerCode,
        base_url: readString(source.base_url || source.baseURL),
        api_key: readString(source.api_key || source.apiKey),
        api_format: API_FORMATS.has(apiFormat) ? apiFormat : 'openai-chat-completions',
        models: normalizeProviderModels(source.models),
        is_active: normalizeBoolean(source.is_active, true)
    };
}

function normalizeProviderRegistry(value) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
    const result = {};
    for (const [code, entry] of Object.entries(value)) {
        const normalized = normalizeProviderEntry(entry, readString(code));
        if (normalized.code && normalized.is_active) result[normalized.code] = normalized;
    }
    return result;
}

function hasOwn(object, property) {
    return Object.prototype.hasOwnProperty.call(object, property);
}

function clampInteger(value, fallback, minimum, maximum) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) return fallback;
    return Math.max(minimum, Math.min(Math.trunc(parsed), maximum));
}

function normalizeBoolean(value, fallback) {
    if (value === true || value === false) return value;
    if (value === 1 || value === '1' || value === 'true') return true;
    if (value === 0 || value === '0' || value === 'false') return false;
    return fallback;
}

function normalizeMagentoOauth(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return Object.fromEntries(
        MAGENTO_OAUTH_FIELDS.map((field) => [field, readString(source[field])])
    );
}

function normalizeImageGeneration(value, provider, selectedModel = null, config = {}) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};
    const size = readString(source.size, process.env.COCKPIT_IMAGE_SIZE || '1024x1024');
    const quality = readString(source.quality, process.env.COCKPIT_IMAGE_QUALITY || 'medium');
    const defaultModel = provider === 'gemini'
        ? process.env.GEMINI_IMAGE_MODEL || 'gemini-3.1-flash-image'
        : process.env.COCKPIT_IMAGE_MODEL || 'gpt-image-2';
    const explicitTransport = normalizeImageTransport(source.transport);
    const modelTransport = normalizeImageTransport(selectedModel?.image_transport);
    const transport = hasOwn(source, 'transport')
        ? explicitTransport
        : explicitTransport
            || (selectedModel?.supports_images ? modelTransport : '')
            || defaultImageTransport({ ...config, provider });
    const configuredModel = hasOwn(source, 'model') ? readString(source.model) : '';

    return {
        enabled: hasOwn(source, 'enabled') ? Boolean(source.enabled) : process.env.IMAGE_GENERATION_ENABLED !== '0',
        // The Responses image tool chooses its GPT Image model internally;
        // direct Images/Gemini adapters instead use this explicit image model.
        model: configuredModel
            || (hasOwn(source, 'model') ? '' : readString(selectedModel?.image_model))
            || defaultModel,
        transport,
        size: IMAGE_SIZES.has(size) ? size : '1024x1024',
        quality: IMAGE_QUALITIES.has(quality) ? quality : 'medium',
        timeout_ms: clampInteger(source.timeout_ms, 180000, 30000, 300000),
        customer_per_hour: clampInteger(source.customer_per_hour, 3, 1, 100),
        customer_per_day: clampInteger(source.customer_per_day, 10, 1, 500),
        guest_per_hour: clampInteger(source.guest_per_hour, 2, 1, 50),
        guest_per_day: clampInteger(source.guest_per_day, 5, 1, 200),
        cooldown_seconds: clampInteger(source.cooldown_seconds, 60, 0, 3600),
        max_concurrent_per_identity: clampInteger(source.max_concurrent_per_identity, 1, 1, 3)
    };
}

function normalizeAgent(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return {
        max_tool_rounds: clampInteger(source.max_tool_rounds, 8, 1, 12),
        max_tool_executions: clampInteger(source.max_tool_executions, 15, 1, 30),
        max_category_calls: clampInteger(source.max_category_calls, 3, 1, 10),
        block_duplicate_tool_calls: normalizeBoolean(source.block_duplicate_tool_calls, true),
        max_output_tokens: clampInteger(source.max_output_tokens, 2048, 256, 8192),
        max_model_history_messages: clampInteger(source.max_model_history_messages, 20, 4, 40),
        max_history_tokens: clampInteger(source.max_history_tokens, 12000, 512, 64000),
        max_tool_context_tokens: clampInteger(source.max_tool_context_tokens, 6000, 256, 24000),
        provider_stream_timeout_ms: clampInteger(source.provider_stream_timeout_ms, 120000, 10000, 300000)
    };
}

function normalizeRateLimits(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return {
        messages_per_minute: clampInteger(source.messages_per_minute, 15, 1, 120),
        product_pages_per_minute: clampInteger(source.product_pages_per_minute, 30, 1, 120),
        address_updates_per_minute: clampInteger(source.address_updates_per_minute, 5, 1, 30),
        address_updates_per_hour: clampInteger(source.address_updates_per_hour, 20, 1, 200)
    };
}

function normalizeCapacity(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return {
        concurrent_model_requests: clampInteger(source.concurrent_model_requests, 32, 1, 1000),
        queue_depth: clampInteger(source.queue_depth, 200, 1, 10000),
        queue_wait_ms: clampInteger(source.queue_wait_ms, 30000, 1000, 300000),
        model_lease_ms: clampInteger(source.model_lease_ms, 180000, 10000, 600000)
    };
}

function normalizeAttachments(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return {
        max_image_bytes: clampInteger(source.max_image_bytes, 4 * 1024 * 1024, 256 * 1024, 16 * 1024 * 1024),
        max_images_per_message: clampInteger(source.max_images_per_message, 4, 1, 4),
        max_total_image_bytes: clampInteger(source.max_total_image_bytes, 6 * 1024 * 1024, 256 * 1024, 8 * 1024 * 1024),
        max_total_encoded_bytes: clampInteger(source.max_total_encoded_bytes, 6 * 1024 * 1024, 512 * 1024, 6 * 1024 * 1024),
        max_total_pixels: clampInteger(source.max_total_pixels, 30_000_000, 1_000_000, 50_000_000),
        vision_concurrency: clampInteger(source.vision_concurrency, 4, 1, 32),
        cost_units_per_minute: clampInteger(source.cost_units_per_minute, 30, 5, 300),
        network_cost_units_per_minute: clampInteger(source.network_cost_units_per_minute, 120, 10, 1000),
        global_cost_units_per_minute: clampInteger(source.global_cost_units_per_minute, 1200, 100, 10000)
    };
}

function normalizeVoice(value, provider, fallbackModel = '') {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};
    const liveSource = source.live && typeof source.live === 'object' && !Array.isArray(source.live)
        ? source.live
        : {};

    return {
        enabled: hasOwn(source, 'enabled') ? Boolean(source.enabled) : true,
        transcription_model: readString(
            source.transcription_model,
            provider === 'gemini'
                ? readString(process.env.GEMINI_VOICE_MODEL, fallbackModel || 'gemini-3.1-flash-lite')
                : 'gpt-4o-mini-transcribe'
        ),
        max_duration_seconds: clampInteger(source.max_duration_seconds, 120, 5, 300),
        max_audio_bytes: clampInteger(source.max_audio_bytes, 4 * 1024 * 1024, 256 * 1024, 4 * 1024 * 1024),
        requests_per_minute: clampInteger(source.requests_per_minute, 6, 1, 30),
        max_concurrent_per_identity: clampInteger(source.max_concurrent_per_identity, 1, 1, 2),
        timeout_ms: clampInteger(source.timeout_ms, 120000, 10000, 180000),
        // Live voice has a provider credential of its own.  A compatible
        // chat endpoint (for example Cockpit) is not assumed to implement
        // OpenAI's Realtime protocol.
        live: {
            enabled: provider === 'openai' && hasOwn(liveSource, 'enabled') && Boolean(liveSource.enabled),
            api_key: provider === 'openai'
                ? readString(liveSource.api_key, process.env.OPENAI_REALTIME_API_KEY || '')
                : '',
            model: provider === 'openai' ? readString(liveSource.model, 'gpt-realtime-1.5') : '',
            max_sessions_per_minute: clampInteger(liveSource.max_sessions_per_minute, 3, 1, 30),
            max_duration_seconds: clampInteger(liveSource.max_duration_seconds, 600, 30, 1800)
        }
    };
}

function normalizeFeatures(value) {
    const source = value && typeof value === 'object' && !Array.isArray(value) ? value : {};

    return {
        // Candidate references already exist in the storefront history
        // contract, so keep that established behaviour on during migration.
        // New guided/proactive/attribution flows remain opt-in until their
        // release gates documented in the Evolution Plan have passed.
        candidate_memory_enabled: normalizeBoolean(source.candidate_memory_enabled, true),
        product_advisor_enabled: normalizeBoolean(source.product_advisor_enabled, false),
        proactive_suggestions_enabled: normalizeBoolean(source.proactive_suggestions_enabled, false),
        analytics_attribution_enabled: normalizeBoolean(source.analytics_attribution_enabled, false),
        guardrails_enabled: normalizeBoolean(source.guardrails_enabled, true)
    };
}

function resolveThoughtLevel(value, models, selectedModel) {
    const selected = Array.isArray(models)
        ? models.find((model) => model?.id === selectedModel)
        : null;
    if (!selected?.reasoning_enabled) return '';

    const available = Array.isArray(selected.reasoning_levels) && selected.reasoning_levels.length > 0
        ? selected.reasoning_levels
        : [];
    const configured = readString(value).toLowerCase();
    if (available.includes(configured)) return configured;
    if (available.includes(selected.reasoning_default_level)) return selected.reasoning_default_level;
    return available[0] || '';
}

export function normalizeConfig(config = {}) {
    const providers = normalizeProviderRegistry(config.providers);
    const provider = readString(config.provider);
    const selectedProvider = providers[provider] || null;
    const selectedConfig = selectedProvider ? { ...config, ...selectedProvider, provider } : config;
    const configuredApiKey = readString(selectedConfig.api_key);

    const models = selectedProvider?.models || normalizeProviderModels(selectedConfig.models);
    const model = readString(selectedConfig.model, models[0]?.id || '');
    const thoughtLevel = resolveThoughtLevel(selectedConfig.thought_level, models, model);
    const selectedModel = models.find((entry) => entry?.id === model) || null;
    const normalized = {
        enabled: hasOwn(selectedConfig, 'enabled') ? Boolean(selectedConfig.enabled) : true,
        persist_guest_history: hasOwn(selectedConfig, 'persist_guest_history') ? Boolean(selectedConfig.persist_guest_history) : false,
        provider,
        model,
        api_key: configuredApiKey,
        name: readString(selectedConfig.name, selectedProvider?.name || provider),
        provider_id: selectedProvider?.provider_id || null,
        api_format: readString(selectedConfig.api_format, selectedProvider?.api_format || ''),
        models,
        thought_level: thoughtLevel,
        providers,
        base_url: readString(selectedConfig.base_url).replace(/\/+$/, ''),
        grounding_model: readString(selectedConfig.grounding_model),
        // Magento is the source of truth for the storefront URL.  The
        // environment value remains only as a backwards-compatible local
        // bootstrap when no Admin snapshot has been synchronized yet.
        magento_base_url: readString(selectedConfig.magento_base_url, process.env.MAGENTO_API_URL || ''),
        agent: normalizeAgent(selectedConfig.agent),
        image_generation: normalizeImageGeneration(selectedConfig.image_generation, provider, selectedModel, {
            api_format: readString(selectedConfig.api_format, selectedProvider?.api_format || ''),
            base_url: readString(selectedConfig.base_url).replace(/\/+$/, ''),
            models,
            model
        }),
        rate_limits: normalizeRateLimits(selectedConfig.rate_limits),
        capacity: normalizeCapacity(selectedConfig.capacity),
        attachments: normalizeAttachments(selectedConfig.attachments),
        voice: normalizeVoice(selectedConfig.voice, provider, model),
        features: normalizeFeatures(selectedConfig.features),
        magento_oauth: normalizeMagentoOauth(selectedConfig.magento_oauth)
    };

    return {
        ...normalized,
        capabilities: getProviderCapabilities(normalized)
    };
}

function normalizeTenantSnapshot(config = {}) {
    const source = config && typeof config === 'object' && !Array.isArray(config) ? config : {};
    const rawStores = source.stores && typeof source.stores === 'object' && !Array.isArray(source.stores)
        ? source.stores
        : {};
    const stores = {};
    for (const [storeCode, value] of Object.entries(rawStores)) {
        if (!STORE_CODE_PATTERN.test(storeCode)) continue;
        stores[storeCode] = normalizeConfig(value);
    }

    return {
        default: normalizeConfig(source.default && typeof source.default === 'object' ? source.default : source),
        stores
    };
}

function normalizeConfigSnapshot(config = {}) {
    const source = config && typeof config === 'object' && !Array.isArray(config) ? config : {};
    const legacy = normalizeTenantSnapshot(source);
    const rawTenants = source.tenants && typeof source.tenants === 'object' && !Array.isArray(source.tenants)
        ? source.tenants
        : {};
    const tenants = {};
    for (const [tenantId, value] of Object.entries(rawTenants)) {
        const normalizedTenantId = normalizeTenantId(tenantId);
        if (!normalizedTenantId) continue;
        tenants[normalizedTenantId] = normalizeTenantSnapshot(value);
    }

    return {
        version: 4,
        tenant_id: normalizeTenantId(source.tenant_id || source.tenantId),
        default: legacy.default,
        stores: legacy.stores,
        tenants
    };
}

function resolveStoreConfig(snapshot, storeCode = '', tenantId = '') {
    const normalizedStoreCode = String(storeCode || '').trim();
    const normalizedTenantId = normalizeTenantId(tenantId);
    const scopedSnapshot = normalizedTenantId && snapshot.tenants?.[normalizedTenantId]
        ? snapshot.tenants[normalizedTenantId]
        : snapshot;
    return scopedSnapshot.stores?.[normalizedStoreCode] || scopedSnapshot.default;
}

function loadConfigFromDisk() {
    if (!fs.existsSync(CONFIG_FILE)) {
        return null;
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
        return normalizeConfigSnapshot(unsealConfig(parsed));
    } catch (error) {
        console.error('Could not read the local AI configuration snapshot:', error.message);
        return null;
    }
}

function persistConfigSnapshot(config) {
    try {
        fs.mkdirSync(CONFIG_DIRECTORY, { recursive: true, mode: 0o700 });
        const temporaryFile = `${CONFIG_FILE}.${process.pid}.tmp`;
        const sealed = sealConfig({
            ...config,
            synced_at: new Date().toISOString()
        });
        fs.writeFileSync(temporaryFile, JSON.stringify(sealed, null, 2), {
            encoding: 'utf8',
            mode: 0o600
        });
        fs.renameSync(temporaryFile, CONFIG_FILE);
        fs.chmodSync(CONFIG_FILE, 0o600);
    } catch (error) {
        console.error('Could not persist the local AI configuration snapshot:', error.message);
        throw new Error('Could not persist the local configuration snapshot.');
    }
}

/**
 * Return the last configuration accepted by the Node service. The service no
 * longer fetches configuration from Magento during a customer chat request.
 */
export const getAiConfigSnapshot = async (runtime = null) => {
    if (runtime) {
        const distributedConfig = await runtime.getConfig();
        if (distributedConfig) {
            const snapshot = normalizeConfigSnapshot(unsealConfig(distributedConfig));
            // Keep the last accepted multi-tenant snapshot available to
            // Magento adapters that receive only the signed site/store scope.
            cachedConfig = { value: snapshot, source: 'distributed_snapshot' };
            return snapshot;
        }
    }

    if (cachedConfig) return cachedConfig.value;

    const config = loadConfigFromDisk() || normalizeConfigSnapshot({});
    cachedConfig = {
        value: config,
        source: fs.existsSync(CONFIG_FILE) ? 'local_snapshot' : 'runtime_environment'
    };
    return config;
};

export const getAiConfig = async (runtime = null, storeCode = '', tenantId = '') => (
    resolveStoreConfig(await getAiConfigSnapshot(runtime), storeCode, tenantId)
);

/**
 * Apply a signed Magento configuration push. Validation of the HMAC request
 * happens in server.js; this function validates and persists only the payload.
 */
export const applyPushedConfig = async (config, runtime = null) => {
    if (!config || typeof config !== 'object' || Array.isArray(config)) {
        throw new Error('Configuration payload must be an object.');
    }

    const rawDefault = config.default && typeof config.default === 'object' ? config.default : config;
    const incomingTenantId = normalizeTenantId(config.tenant_id || config.tenantId);
    const requestedProvider = readString(rawDefault.provider);
    const rawProviders = rawDefault.providers && typeof rawDefault.providers === 'object' && !Array.isArray(rawDefault.providers)
        ? rawDefault.providers
        : null;
    // A synchronized Magento registry is authoritative. Reject a selection
    // that is missing or inactive instead of falling back to a different
    // provider and potentially sending its credentials to the model API.
    if (requestedProvider && rawProviders && !Object.prototype.hasOwnProperty.call(rawProviders, requestedProvider)) {
        const error = new Error('Selected provider is not present in the active Magento provider registry.');
        error.code = 'CONFIG_PROVIDER_NOT_CONFIGURED';
        error.status = 422;
        throw error;
    }

    const rawStores = config.stores && typeof config.stores === 'object' && !Array.isArray(config.stores)
        ? config.stores
        : {};
    for (const [storeCode, storeConfig] of Object.entries(rawStores)) {
        if (!STORE_CODE_PATTERN.test(storeCode)) {
            throw new Error('Store configuration is invalid.');
        }
    }

    const incomingSnapshot = normalizeTenantSnapshot({
        default: rawDefault,
        stores: rawStores
    });
    const validation = [
        validateProviderConfiguration(incomingSnapshot.default, 'default'),
        ...Object.entries(incomingSnapshot.stores).map(([storeCode, storeConfig]) => (
            validateProviderConfiguration(storeConfig, `store:${storeCode}`)
        ))
    ];
    const errors = validation.flatMap((result) => result.errors);
    if (errors.length) {
        const error = new Error(errors.map((item) => `[${item.scope}] ${item.message}`).join(' '));
        error.code = 'CONFIG_VALIDATION_FAILED';
        error.status = 422;
        throw error;
    }
    const previous = incomingTenantId
        ? await getAiConfigSnapshot(runtime)
        : null;
    const normalized = incomingTenantId
        ? normalizeConfigSnapshot({
            version: 4,
            tenant_id: incomingTenantId,
            default: incomingSnapshot.default,
            stores: incomingSnapshot.stores,
            tenants: {
                ...(previous?.tenants || {}),
                [incomingTenantId]: incomingSnapshot
            }
        })
        : normalizeConfigSnapshot({
            default: incomingSnapshot.default,
            stores: incomingSnapshot.stores
        });
    normalized.validation = {
        warnings: validation.flatMap((result) => result.warnings)
    };

    persistConfigSnapshot(normalized);
    if (runtime) {
        await runtime.setConfig(sealConfig(normalized));
    }
    cachedConfig = {
        value: normalized,
        source: 'magento_push'
    };

    return normalized;
};

export const clearConfigCache = () => {
    cachedConfig = null;
};

/** Return the synchronized Magento website URL for a store view. */
export function getMagentoBaseUrl(storeCode = '', tenantId = '') {
    const snapshot = cachedConfig?.value || loadConfigFromDisk() || normalizeConfigSnapshot({});
    const config = resolveStoreConfig(snapshot, storeCode, tenantId);
    return readString(config.magento_base_url, process.env.MAGENTO_API_URL || '').replace(/\/+$/, '');
}
